# Generated by Django 5.1.1 on 2025-08-27 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('cost_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_name', models.CharField(max_length=100)),
                ('grade_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalHarvest',
            fields=[
                ('local_harvest_id', models.AutoField(primary_key=True, serialize=False)),
                ('harvest_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('market_id', models.AutoField(primary_key=True, serialize=False)),
                ('market_name', models.CharField(max_length=100)),
                ('market_address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('partner_name', models.CharField(max_length=100)),
                ('partner_address', models.TextField(blank=True, null=True)),
                ('partner_phone', models.PositiveBigIntegerField()),
                ('start_date', models.DateField()),
                ('contract_duration', models.PositiveIntegerField()),
                ('land_area', models.PositiveIntegerField(null=True)),
                ('partner_status', models.BooleanField(default=None, null=True)),
                ('min_quantity', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_unit', models.CharField(max_length=100)),
                ('product_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('production_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('cost_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('cost_name', models.CharField(max_length=100)),
                ('cost_amount', models.PositiveIntegerField()),
                ('cost_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.costtype')),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('commodity_id', models.AutoField(primary_key=True, serialize=False)),
                ('commodity_name', models.CharField(max_length=100)),
                ('purchase_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('grade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.grade')),
            ],
        ),
        migrations.CreateModel(
            name='LocalHarvestDetail',
            fields=[
                ('local_harvest_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.commodity')),
                ('local_harvest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.localharvest')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerHarvest',
            fields=[
                ('partner_harvest_id', models.AutoField(primary_key=True, serialize=False)),
                ('harvest_date', models.DateField()),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerHarvestDetail',
            fields=[
                ('partner_harvest_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.commodity')),
                ('partner_harvest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.partnerharvest')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionDetail',
            fields=[
                ('production_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_quantity', models.PositiveIntegerField()),
                ('product_status', models.CharField(max_length=100, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.product')),
                ('production_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.production')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('market_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.market')),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('sale_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('commodity_quantity', models.PositiveIntegerField(null=True)),
                ('product_quantity', models.PositiveIntegerField(null=True)),
                ('commodity_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guava.commodity')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guava.product')),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.sale')),
            ],
        ),
    ]
